a = input()
print("Tipo primitivo", type(a))
print("Apenas espaço", a.isspace())
print("Número", a.isnumeric())
print("Alfabetico", a.isalpha())
print("Alfanumerico", a.isalnum())
print("Maiúsculas", a.isupper())
print("Minúsculas", a.islower())
print("Capitalizada", a.istitle())